package com.adam.simplehibernate;
// Generated Jun 2, 2016 11:04:35 PM by Hibernate Tools 4.3.1



/**
 * Mahasiswa generated by hbm2java
 */

public class Mahasiswa  implements java.io.Serializable {


     private Integer id;
     private String npm;
     private String nama;
     private String tempatLahir;
     private String tanggalLahir;
     private String jenisKelamin;
     private String alamat;

    public Mahasiswa() {
    }

    public Mahasiswa(String npm, String nama, String tempatLahir, String tanggalLahir, String jenisKelamin, String alamat) {
       this.npm = npm;
       this.nama = nama;
       this.tempatLahir = tempatLahir;
       this.tanggalLahir = tanggalLahir;
       this.jenisKelamin = jenisKelamin;
       this.alamat = alamat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNpm() {
        return this.npm;
    }
    
    public void setNpm(String npm) {
        this.npm = npm;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getTempatLahir() {
        return this.tempatLahir;
    }
    
    public void setTempatLahir(String tempatLahir) {
        this.tempatLahir = tempatLahir;
    }
    public String getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(String tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


